# Generated by Django 5.2.6 on 2025-11-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='message',
            new_name='extra_description',
        ),
        migrations.AddField(
            model_name='request',
            name='payment_choice',
            field=models.CharField(blank=True, choices=[('Online', 'Online Payment'), ('Cash', 'Cash on Meetup')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='requested_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
