# Generated by Django 5.2.6 on 2025-11-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_message_request_extra_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requested_date_time',
            field=models.CharField(blank=True, help_text="e.g., 'Tomorrow around 5 PM', or 'Weekend anytime'", max_length=100, null=True),
        ),
    ]
