# Generated by Django 5.2.6 on 2025-11-14 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarterProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offered_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barter_offers', to='core.skill')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barter_proposal', to='core.request')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_type', models.CharField(choices=[('Voluntary', 'Voluntary (Free)'), ('Barter', 'Barter (Skill for Skill)'), ('Low-Cost', 'Low-Cost (Small Fee)')], max_length=20)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('barter_proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.barterproposal')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_transactions', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.request')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
