# Generated by Django 5.2.6 on 2025-11-14 07:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_barterproposal_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating', to='core.request')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.skill')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('request', 'rater')},
            },
        ),
    ]
