# Generated by Django 5.2.6 on 2025-11-29 10:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customuser_search_vector_skill_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('request_received', 'New Skill Request'), ('request_accepted', 'Request Accepted'), ('request_declined', 'Request Declined'), ('session_reminder', 'Session Reminder'), ('new_message', 'New Message'), ('feedback_received', 'Feedback Received'), ('barter_proposal', 'Barter Proposal'), ('session_completed', 'Session Completed')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_request', models.BooleanField(default=True)),
                ('email_request_accepted', models.BooleanField(default=True)),
                ('email_schedule_reminders', models.BooleanField(default=True)),
                ('email_new_messages', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('push_session_reminders', models.BooleanField(default=True)),
                ('feedback_reminders', models.BooleanField(default=True)),
                ('feedback_received', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='core_messag_recipie_ffa7b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='core_messag_convers_d2b392_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(db_index=True, default='temporary', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='payment_choice',
            field=models.CharField(blank=True, choices=[('online', 'Online Payment'), ('cash', 'Cash on Meetup'), ('negotiable', 'Negotiable'), ('free', 'Free (Skill Exchange)'), ('paid', 'Paid Session')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.request'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_about', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='core_notifi_recipie_4d7e73_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx'),
        ),
    ]
